<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio Filtrado de Datos

En este laboratorio usaremos el DataFrame creado en la lección anterior resultado de la unión de los conjuntos de datos compartidos contigo. 

**Instrucciones:**

1. Lee cuidadosamente el enunciado de cada ejercicio.

2. Implementa la solución en la celda de código proporcionada.

In [57]:
import pandas as pd

In [58]:
# Carga el dataset de trabajo
df_merged = pd.read_csv("datos/df_merged.csv")
df_merged.drop(columns=['Unnamed: 0'], inplace=True)
df_merged.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,2.5,English/Japanese,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...
1,2.6,Spanish,s2105,Movie,Dark Forces,Bernardo Arellano,"Tenoch Huerta, Eréndira Ibarra, Dale Carley, A...",Mexico,"August 21, 2020",2020,TV-MA,81 min,"Horror Movies, Independent Movies, Internation...","In search of his sister, a renegade criminal s..."
2,2.6,Italian,s3095,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ..."
3,3.2,English,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son..."
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...

#### Ejercicio 1: ¿Cuáles son todos los títulos lanzados en 2021 que son del tipo 'Movie'?

In [59]:
condicion_movie = df_merged['type'] == 'Movie'
condicion_2021 = df_merged['release_year'] == 2021

df_1 = df_merged[(condicion_movie) & (condicion_2021)]

df_1.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
9,4.1,Hindi,s872,Movie,Sardar Ka Grandson,Kaashvie Nair,"Arjun Kapoor, Neena Gupta, Rakul Preet Singh, ...",India,"May 18, 2021",2021,TV-14,140 min,"Comedies, Dramas, International Movies",A devoted grandson’s mission to reunite his ai...
17,4.3,Korean,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,NaN,"Comedies, International Movies","With the peak of his career long behind him, a..."
21,4.4,Hindi,s1266,Movie,The Girl on the Train,Ribhu Dasgupta,"Parineeti Chopra, Aditi Rao Hydari, Kirti Kulh...",India,"February 26, 2021",2021,TV-MA,120 min,"International Movies, Thrillers",A troubled divorcée fixates on a seemingly ide...
22,4.4,English,s1089,Movie,Thunder Force,Ben Falcone,"Melissa McCarthy, Octavia Spencer, Jason Batem...",United States,"April 9, 2021",2021,PG-13,107 min,"Action & Adventure, Comedies",Two childhood best friends reunite as an unlik...
24,4.5,Dutch,s1110,Movie,Just Say Yes,"Appie Boudellah, Aram van de Rest","Yolanthe Cabau, Noortje Herlaar, Kim-Lian van ...",Netherlands,"April 2, 2021",2021,TV-MA,98 min,"Comedies, International Movies, Romantic Movies",Incurable romantic Lotte finds her life upende...

#### Ejercicio 2: ¿Qué títulos tienen una duración de 90 minutos? Muestra solo las columnas de título y de duración.

In [60]:
condicion_2 = df_merged['duration'] == '90 min'
df_2 = df_merged[condicion_2][['title', 'duration']]
df_2.head()

                   title duration
23          Fatal Affair   90 min
123  One-Way to Tomorrow   90 min
139             Good Sam   90 min
149      The Wrong Missy   90 min
155         American Son   90 min

#### Ejercicio 3: ¿Cuáles son todos los títulos del país 'India' lanzados después de 2018?

In [61]:
condicion_india = df_merged['country'] == 'India'
condicion_despues_2018 = df_merged['release_year'] > 2018

df_3 = df_merged[(condicion_india) & (condicion_despues_2018)]
df_3.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...
5,3.5,Hindi,s3335,Movie,Drive,Tarun Mansukhani,"Jacqueline Fernandez, Sushant Singh Rajput, Bo...",India,"November 1, 2019",2019,TV-14,119 min,"Action & Adventure, International Movies",A notorious thief allies with a street racer f...
9,4.1,Hindi,s872,Movie,Sardar Ka Grandson,Kaashvie Nair,"Arjun Kapoor, Neena Gupta, Rakul Preet Singh, ...",India,"May 18, 2021",2021,TV-14,140 min,"Comedies, Dramas, International Movies",A devoted grandson’s mission to reunite his ai...
15,4.3,Hindi,s3061,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."
21,4.4,Hindi,s1266,Movie,The Girl on the Train,Ribhu Dasgupta,"Parineeti Chopra, Aditi Rao Hydari, Kirti Kulh...",India,"February 26, 2021",2021,TV-MA,120 min,"International Movies, Thrillers",A troubled divorcée fixates on a seemingly ide...

#### Ejercicio 4: ¿Qué títulos tienen clasificación 'TV-14' o 'R'?

In [62]:
condicion_4 = df_merged['rating'].isin(['TV-14', 'R'])
df_4 = df_merged[condicion_4]
df_4.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...
5,3.5,Hindi,s3335,Movie,Drive,Tarun Mansukhani,"Jacqueline Fernandez, Sushant Singh Rajput, Bo...",India,"November 1, 2019",2019,TV-14,119 min,"Action & Adventure, International Movies",A notorious thief allies with a street racer f...
9,4.1,Hindi,s872,Movie,Sardar Ka Grandson,Kaashvie Nair,"Arjun Kapoor, Neena Gupta, Rakul Preet Singh, ...",India,"May 18, 2021",2021,TV-14,140 min,"Comedies, Dramas, International Movies",A devoted grandson’s mission to reunite his ai...
11,4.1,Indonesian,s1982,Movie,Whipped,Chandra Liow,"Andovi da Lopez, Jovial da Lopez, Chandra Liow...",Indonesia,"September 18, 2020",2020,TV-14,98 min,"Comedies, International Movies, Romantic Movies",Four buddies attend a class taught by a love g...
16,4.3,English,s2898,Movie,The Last Thing He Wanted,Dee Rees,"Anne Hathaway, Ben Affleck, Willem Dafoe, Toby...",United States,"February 21, 2020",2020,R,116 min,"Dramas, Thrillers",A hard-hitting reporter becomes entangled in t...

#### Ejercicio 5: ¿Cuáles son los títulos dirigidos por 'Christopher Nolan' o 'Martin Scorsese'? ¿Cuántos a dirigido cada uno de los directores?

In [63]:
condicion_5 = df_merged['director'].isin(['Christopher Nolan', 'Martin Scorsese'])

df_5 = df_merged[condicion_5]

df_5.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
496,7.8,English,s3228,Movie,The Irishman,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Harvey K...",United States,"November 27, 2019",2019,R,209 min,Dramas,Hit man Frank Sheeran looks back at the secret...
851,NaN,NaN,s341,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...","United States, United Kingdom","August 1, 2021",2010,PG-13,148 min,"Action & Adventure, Sci-Fi & Fantasy, Thrillers",A troubled thief who extracts secrets from peo...
1821,NaN,NaN,s1359,Movie,Shutter Island,Martin Scorsese,"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley,...",United States,"February 1, 2021",2010,R,139 min,Thrillers,A U.S. marshal's troubling visions compromise ...
2950,NaN,NaN,s2633,Movie,No Direction Home: Bob Dylan,Martin Scorsese,"Bob Dylan, Joan Baez, Dave Van Ronk, Peter Yar...","United Kingdom, United States, Japan","April 25, 2020",2005,TV-MA,208 min,"Documentaries, Music & Musicals",Featuring rare concert footage and interviews ...
3154,NaN,NaN,s2861,Movie,Hugo,Martin Scorsese,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","United Kingdom, United States, France","March 1, 2020",2011,PG,127 min,"Children & Family Movies, Dramas","Living inside a Paris train station, an orphan..."

In [64]:
df_5.groupby('director')['title'].count().reset_index()

            director  title
0  Christopher Nolan      1
1    Martin Scorsese     12

#### Ejercicio 6: ¿Qué títulos pertenecen a los países 'United States', 'United Kingdom' o 'Canada'? Dentro de estos países, ¿cuántas películas tienen más de un lenguaje?

In [65]:
cond_united = df_merged['country'].str.contains('United States', case=False)
cond_kingdom = df_merged['country'].str.contains('United Kingdom', case=False)
cond_canada = df_merged['country'].str.contains('Canada', case=False)

df_6 = df_merged[(cond_united) | (cond_kingdom) | (cond_canada)]
df_6.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,2.5,English/Japanese,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...
3,3.2,English,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son..."
7,3.7,English,s2425,Movie,The Last Days of American Crime,Olivier Megaton,"Edgar Ramírez, Michael Pitt, Anna Brewster, Pa...",United States,"June 5, 2020",2020,TV-MA,149 min,"Action & Adventure, Dramas, Independent Movies",A bank robber joins a plot to commit one final...
8,3.9,English,s4973,Movie,Paradox,Daryl Hannah,"Neil Young, Lukas Nelson, Micah Nelson, Corey ...",United States,"March 23, 2018",2018,TV-MA,74 min,"Dramas, Independent Movies, Music & Musicals",Neil Young and his band of outlaws sow seeds o...
13,4.2,English,s5710,Movie,Mercy,Chris Sparling,"James Wolk, Caitlin Fitzgerald, Tom Lipinski, ...",United States,"November 22, 2016",2016,TV-MA,NaN,"Dramas, Thrillers",Two brothers clash with their half-siblings wh...

In [66]:
print("De estas, tienen varios lenguages\n")
df_6[df_6['Language'].str.contains('/', na=False)].shape[0]

De estas, tienen varios lenguages

19

#### Ejercicio 7: ¿Qué títulos fueron lanzados entre 2015 y 2020, inclusive?

In [67]:
condicion_7 = df_merged['release_year'].between(2015, 2020, inclusive='both')
df_7 = df_merged[condicion_7]
df_7.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,2.5,English/Japanese,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...
1,2.6,Spanish,s2105,Movie,Dark Forces,Bernardo Arellano,"Tenoch Huerta, Eréndira Ibarra, Dale Carley, A...",Mexico,"August 21, 2020",2020,TV-MA,81 min,"Horror Movies, Independent Movies, Internation...","In search of his sister, a renegade criminal s..."
2,2.6,Italian,s3095,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ..."
3,3.2,English,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son..."
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...

#### Ejercicio 8: ¿Cuáles son los títulos cuya puntuación en IMDb está entre 6.5 y 8.0 y que no sepamos cual es su duración?

In [68]:
condicion_8 = df_merged['IMDB Score'].between(6.5, 8.0)
condicion_nulo = df_merged['duration'].isnull()

df_8 = df_merged[(condicion_8) & (condicion_nulo)]
df_8.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
295,6.5,English,s2085,Movie,All Together Now,Brett Haley,"Auli'i Cravalho, Justina Machado, Rhenzy Feliz...",United States,"August 29, 2020",2020,PG,NaN,Dramas,"An optimistic, talented teen clings to a huge ..."
299,6.5,Hindi,s3789,Movie,Chopsticks,Sachin Yardi,"Abhay Deol, Mithila Palkar, Vijay Raaz",India,"May 31, 2019",2019,TV-MA,NaN,"Comedies, Dramas, Independent Movies",A gifted but insecure woman embarks on a trans...
303,6.5,English,s5253,Movie,Gerald's Game,Mike Flanagan,"Carla Gugino, Bruce Greenwood, Henry Thomas, C...",United States,"September 29, 2017",2017,TV-MA,NaN,"Horror Movies, Thrillers","When her husband's sex game goes wrong, Jessie..."
304,6.5,English,s1776,Movie,His House,Remi Weekes,"Ṣọpẹ́ Dìrísù, Wunmi Mosaku, Matt Smith, Malaik...",United Kingdom,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, Independent Movies",As a young couple from war-torn South Sudan se...
308,6.5,English,s911,Movie,Monster,Anthony Mandler,"Kelvin Harrison Jr., Jennifer Hudson, Jeffrey ...",United States,"May 7, 2021",2021,TV-MA,NaN,Dramas,A talented teen implicated in a robbery-turned...

#### Ejercicio 9: ¿Cuáles son las películas cuya duración de 90 y 150 minutos?

In [69]:
condicion_9 = df_merged['duration'].isin(['90 min', '150 min'])

df_9 = df_merged[condicion_9]
df_9.sample(5)

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5926,NaN,NaN,s5927,Movie,E-Team,"Katy Chevigny, Ross Kauffman",NaN,United States,"October 24, 2014",2014,TV-MA,90 min,Documentaries,The courageous investigators of Human Rights W...
4252,NaN,NaN,s4061,Movie,Radio Rebel,Peter Howitt,"Debby Ryan, Sarena Parmar, Adam DiMarco, Merri...",United States,"March 1, 2019",2012,TV-G,90 min,"Children & Family Movies, Comedies",Shy student Tara has a secret identity: She is...
6614,NaN,NaN,s6615,Movie,Disciples Of The 36th Chamber,Chia-Liang Liu,"Hou Hsiao, Gordon Liu, Lily Li, Jason Pai Piao...",Hong Kong,"August 16, 2018",1985,TV-14,90 min,"Action & Adventure, International Movies",Shaolin monk San Te returns to protect a fello...
6200,NaN,NaN,s6201,Movie,Avengers: Infinity War,"Anthony Russo, Joe Russo","Robert Downey Jr., Josh Brolin, Mark Ruffalo, ...",United States,"December 25, 2018",2018,PG-13,150 min,"Action & Adventure, Sci-Fi & Fantasy",Superheroes amass to stop intergalactic sociop...
7943,NaN,NaN,s7944,Movie,Satrangi Re,Aditya Sarpotdar,"Amruta Khanvilkar, Vidyadhar Joshi, Subodh Bhave",India,"March 15, 2018",2012,TV-14,150 min,"Dramas, International Movies, Music & Musicals",Friends in their last year of college contempl...

#### Ejercicio 10: ¿Cuáles son los títulos que contienen la palabra 'Love' en su título y que sean de tipo TV Show?

In [70]:
condicion_10 = df_merged['title'].str.contains(pat =r"\b^[Ll]ove", case=False, na=False)
condicion_tv_show = df_merged['type'] == 'TV Show'

df_10 = df_merged[(condicion_10) & (condicion_tv_show)]
df_10.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
537,NaN,NaN,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...
1241,NaN,NaN,s732,TV Show,Love (ft. Marriage and Divorce),NaN,"Sung Hoon, Lee Tae-gon, Park Joo-mi, Lee Ga-ry...",South Korea,"June 12, 2021",2021,TV-14,2 Seasons,"International TV Shows, TV Dramas",Everything comes unraveling for three successf...
1385,NaN,NaN,s884,TV Show,"Love, Death & Robots",NaN,"Topher Grace, Mary Elizabeth Winstead, Gary Co...",United States,"May 14, 2021",2021,TV-MA,2 Seasons,"TV Action & Adventure, TV Horror, TV Sci-Fi & ...","Terrifying creatures, wicked surprises and dar..."
1525,NaN,NaN,s1033,TV Show,Love Naggers,NaN,"Seo Jang-hoon, Kim Sook, Han Hye-jin, Kwak Jun...",South Korea,"April 16, 2021",2021,TV-14,NaN,"International TV Shows, Stand-Up Comedy & Talk...","From the quirky to the scandalous, any relatio..."
1688,NaN,NaN,s1211,TV Show,Love Alarm,NaN,"Kim So-hyun, Jung Ga-ram, Song Kang, Ko Min-si...",South Korea,"March 12, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Korean TV Shows, Roman...",In a world where an app alerts people if someo...

#### Ejercicio 11: ¿Cuáles son los títulos en los que el director tiene el apellido 'Johnson'?

In [71]:
condicion_11 = df_merged['director'].str.contains(' Johnson', case=False, na=False)

df_11 = df_merged[condicion_11]
df_11.head()

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
122,5.6,English,s2053,Movie,"Love, Guaranteed",Mark Steven Johnson,"Rachael Leigh Cook, Damon Wayans Jr., Heather ...",United States,"September 3, 2020",2020,TV-PG,NaN,"Comedies, Independent Movies, Romantic Movies",Sparks fly when a crusading but cash-strapped ...
195,6.0,English,s4034,Movie,Juanita,Clark Johnson,"Alfre Woodard, Adam Beach, LaTanya Richardson ...",United States,"March 8, 2019",2019,TV-MA,90 min,"Dramas, Independent Movies, Romantic Movies","Burdened by troubles in life and love, a mothe..."
244,6.3,English,s4834,Movie,Alex Strangelove,Craig Johnson,"Daniel Doheny, Madeline Weinstein, Antonio Mar...",United States,"June 8, 2018",2018,TV-MA,NaN,"Comedies, Dramas, Independent Movies",High school senior Alex Truelove's plan to los...
479,7.5,English,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1339,NaN,NaN,s830,Movie,Dog Gone Trouble,Kevin Johnson,"Big Sean, Pamela Adlon, Lucy Hale, Marissa Jar...",NaN,"May 28, 2021",2021,TV-Y7,NaN,"Children & Family Movies, Comedies",The privileged life of a pampered dog named Tr...

#### Ejercicio 12: ¿Tenemos algún documental ('Documentaries') de Mike Tyson?

### Este lo ha sacado buscando en internet como se llama el documental de Myke Tyson

In [72]:
condicion_12 = df_merged['listed_in'].str.contains('Documentaries', case=False, na=False)
condicion_tyson = df_merged['title'].str.contains('tyson', case=False, na=False)

df_12 = df_merged[(condicion_12) & (condicion_tyson)]
df_12

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8651,NaN,NaN,s8652,Movie,Tyson,James Toback,"Mike Tyson, Trevor Berbick","United States, France","March 1, 2019",2008,R,90 min,"Documentaries, Sports Movies","In this surprisingly emotional documentary, he..."

#### Ejercicio 13: Selecciona solo las columnas 'title', 'country' y 'release_year' del dataset.

In [73]:
df_merged.filter(['title', 'country', 'release_year'])

                title                country  release_year
0     Enter the Anime   United States, Japan          2019
1         Dark Forces                 Mexico          2020
2             The App                  Italy          2019
3      The Open House  Canada, United States          2018
4         Kaali Khuhi                  India          2020
...               ...                    ...           ...
8802           Zodiac          United States          2007
8803      Zombie Dumb                    NaN          2018
8804       Zombieland          United States          2009
8805             Zoom          United States          2006
8806           Zubaan                  India          2015

[8807 rows x 3 columns]

#### Ejercicio 14: Filtra las columnas que contienen la palabra 'date'.

In [74]:
df_merged.filter(regex=r"\s?[Dd]ate")

             date_added
0        August 5, 2019
1       August 21, 2020
2     December 26, 2019
3      January 19, 2018
4      October 30, 2020
...                 ...
8802  November 20, 2019
8803       July 1, 2019
8804   November 1, 2019
8805   January 11, 2020
8806      March 2, 2019

[8807 rows x 1 columns]

#### Ejercicio 15: Usando `query()`, filtra todos los títulos del país 'France' con una duración de 80 minutos.

In [75]:
df_merged.query("country == 'France' and duration == '80 min'")

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5533,NaN,NaN,s5475,Movie,Arès,Jean-Patrick Benes,"Ola Rapace, Micha Lescot, Thierry Hancisse, Hé...",France,"May 23, 2017",2016,TV-MA,80 min,"Action & Adventure, International Movies, Sci-...",A futuristic France tries to keep its people f...

In [76]:
df_merged

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,2.5,English/Japanese,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...
1,2.6,Spanish,s2105,Movie,Dark Forces,Bernardo Arellano,"Tenoch Huerta, Eréndira Ibarra, Dale Carley, A...",Mexico,"August 21, 2020",2020,TV-MA,81 min,"Horror Movies, Independent Movies, Internation...","In search of his sister, a renegade criminal s..."
2,2.6,Italian,s3095,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ..."
3,3.2,English,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son..."
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,NaN,NaN,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,NaN,NaN,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,NaN,NaN,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,NaN,NaN,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,NaN,NaN,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

#### Ejercicio 16: Filtra los títulos que son películas ('Movie') y fueron lanzados antes de 2010.

In [77]:
df_merged.query("type == 'Movie' and release_year < 2010")

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
519,NaN,NaN,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
534,NaN,NaN,s23,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj...",NaN,"September 21, 2021",1996,TV-PG,161 min,"Comedies, International Movies",Newly divorced and denied visitation rights wi...
536,NaN,NaN,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
538,NaN,NaN,s27,Movie,Minsara Kanavu,Rajiv Menon,"Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P....",NaN,"September 21, 2021",1997,TV-PG,147 min,"Comedies, International Movies, Music & Musicals",A tangled love triangle ensues when a man fall...
553,NaN,NaN,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8793,NaN,NaN,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,NaN,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...
8799,NaN,NaN,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8802,NaN,NaN,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,NaN,NaN,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,NaN,NaN,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."

#### Ejercicio 17: Encuentra los 10 títulos con las puntuaciones más altas en IMDb.

In [82]:
df_merged.sort_values(by="IMDB Score", ascending=False).head(10)

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
512,9.0,English,s1887,Movie,David Attenborough: A Life on Our Planet,"Alastair Fothergill, Jonnie Hughes, Keith Scholey",David Attenborough,"United States, United Kingdom","October 4, 2020",2020,PG,84 min,Documentaries,"A broadcaster recounts his life, and the evolu..."
511,8.5,English,s4294,Movie,Springsteen on Broadway,Thom Zimny,Bruce Springsteen,United States,"December 16, 2018",2018,TV-MA,153 min,Music & Musicals,Bruce Springsteen shares personal stories from...
510,8.4,English/Ukranian/Russian,s5894,Movie,Winter on Fire: Ukraine's Fight for Freedom,Evgeny Afineevsky,NaN,"United Kingdom, Ukraine, United States","October 9, 2015",2015,TV-MA,NaN,"Documentaries, International Movies","Over 93 days in Ukraine, what started as peace..."
508,8.3,English,s5153,Movie,Cuba and the Cameraman,Jon Alpert,NaN,United States,"November 24, 2017",2017,TV-14,NaN,Documentaries,Emmy-winning filmmaker Jon Alpert chronicles t...
509,8.3,English,s3387,Movie,Dancing with the Birds,Huw Cordey,Stephen Fry,United States,"October 23, 2019",2019,TV-PG,52 min,Documentaries,From ruffling their majestic feathers to naili...
507,8.2,Spanish,s1858,Movie,The Three Deaths of Marisela Escobedo,Carlos Pérez Osorio,NaN,Mexico,"October 14, 2020",2020,TV-MA,110 min,"Documentaries, International Movies",This documentary examines a mother's tireless ...
505,8.2,English,s3274,Movie,Klaus,Sergio Pablos,"Jason Schwartzman, J.K. Simmons, Rashida Jones...","Spain, United Kingdom","November 15, 2019",2019,PG,98 min,"Children & Family Movies, Comedies",A selfish postman and a reclusive toymaker for...
506,8.2,English,s1172,Movie,Seaspiracy,Ali Tabrizi,NaN,United States,"March 24, 2021",2021,TV-14,90 min,Documentaries,"Passionate about ocean life, a filmmaker sets ..."
502,8.1,English,s5377,Movie,Chasing Coral,Jeff Orlowski,NaN,United States,"July 14, 2017",2017,TV-PG,NaN,Documentaries,"Divers, scientists and photographers around th..."
504,8.1,English,s2098,Movie,Rising Phoenix,NaN,NaN,United Kingdom,"August 26, 2020",2020,PG-13,107 min,"Documentaries, International Movies, Sports Mo...",Elite athletes and insiders reflect on the Par...

#### Ejercicio 18: Encuentra los 5 títulos con las puntuaciones más bajas en IMDb.

In [83]:
df_merged.sort_values(by="IMDB Score", ascending=True).head(10)

,IMDB Score,Language,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,2.5,English/Japanese,s3624,Movie,Enter the Anime,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan","August 5, 2019",2019,TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...
2,2.6,Italian,s3095,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ..."
1,2.6,Spanish,s2105,Movie,Dark Forces,Bernardo Arellano,"Tenoch Huerta, Eréndira Ibarra, Dale Carley, A...",Mexico,"August 21, 2020",2020,TV-MA,81 min,"Horror Movies, Independent Movies, Internation...","In search of his sister, a renegade criminal s..."
3,3.2,English,s5074,Movie,The Open House,"Matt Angel, Suzanne Coote","Dylan Minnette, Piercey Dalton, Patricia Bethu...","Canada, United States","January 19, 2018",2018,TV-MA,NaN,"Horror Movies, Thrillers","Following a tragedy, a mother and her teen son..."
4,3.4,Hindi,s1778,Movie,Kaali Khuhi,Terrie Samundra,"Shabana Azmi, Leela Samson, Sanjeeda Sheikh, S...",India,"October 30, 2020",2020,TV-14,NaN,"Horror Movies, International Movies",When a restless spirit curses a village that h...
5,3.5,Hindi,s3335,Movie,Drive,Tarun Mansukhani,"Jacqueline Fernandez, Sushant Singh Rajput, Bo...",India,"November 1, 2019",2019,TV-14,119 min,"Action & Adventure, International Movies",A notorious thief allies with a street racer f...
6,3.7,Turkish,s1595,Movie,Leyla Everlasting,NaN,"Demet Akbağ, Haluk Bilginer, Elçin Sangu, Fıra...",Turkey,"December 4, 2020",2020,TV-MA,113 min,"Comedies, International Movies","A resilient housewife, her husband and their m..."
7,3.7,English,s2425,Movie,The Last Days of American Crime,Olivier Megaton,"Edgar Ramírez, Michael Pitt, Anna Brewster, Pa...",United States,"June 5, 2020",2020,TV-MA,149 min,"Action & Adventure, Dramas, Independent Movies",A bank robber joins a plot to commit one final...
8,3.9,English,s4973,Movie,Paradox,Daryl Hannah,"Neil Young, Lukas Nelson, Micah Nelson, Corey ...",United States,"March 23, 2018",2018,TV-MA,74 min,"Dramas, Independent Movies, Music & Musicals",Neil Young and his band of outlaws sow seeds o...
10,4.1,Korean,s1644,Movie,The Call,Lee Chung-hyun,"Park Shin-hye, Jun Jong-seo, Kim Sung-ryoung, ...",South Korea,"November 27, 2020",2020,TV-MA,112 min,"International Movies, Thrillers",Connected by phone in the same home but 20 yea...

#### Ejercicio 19: Filtra todos los títulos que no tienen un director asignado (valores nulos en la columna 'director').

In [92]:
cond_19 = df_merged['director'] == 'Nan'
df_19 = df_merged[cond_19]
df_19

Empty DataFrame
Columns: [IMDB Score, Language, show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

#### Ejercicio 20: Filtra todos los títulos que tienen información completa en las columnas 'title', 'country' y 'IMDB Score'.

In [107]:
cond_title = df_merged['title'].notnull() == True
cond_country = df_merged['country'].notnull() == True
cond_IMBD = df_merged['IMDB Score'].notnull() == True

df_20 = df_merged[cond_title & cond_country & cond_IMBD]
df_20[['title', 'country', 'IMDB Score']]

,title,country,IMDB Score
0,Enter the Anime,"United States, Japan",2.5
1,Dark Forces,Mexico,2.6
2,The App,Italy,2.6
3,The Open House,"Canada, United States",3.2
4,Kaali Khuhi,India,3.4
...,...,...,...
508,Cuba and the Cameraman,United States,8.3
509,Dancing with the Birds,United States,8.3
510,Winter on Fire: Ukraine's Fight for Freedom,"United Kingdom, Ukraine, United States",8.4
511,Springsteen on Broadway,United States,8.5
512,David Attenborough: A Life on Our Planet,"United States, United Kingdom",9.0

#### Ejercicio 21: Identifica si hay títulos duplicados en la columna 'title'.

In [111]:
df_merged[df_merged['title'].duplicated()]

Empty DataFrame
Columns: [IMDB Score, Language, show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []